# Generated by Django 4.2 on 2024-08-13 18:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Укажите место выполнения', max_length=150, verbose_name='Место')),
                ('time', models.TimeField(default=django.utils.timezone.now, help_text='Укажите время выполнения', verbose_name='Время')),
                ('action', models.CharField(help_text='Укажите действие привычки', verbose_name='Действие')),
                ('nice_habit', models.BooleanField(help_text='Укажите признак приятной привычки', verbose_name='Признак привычки')),
                ('periodicity', models.PositiveSmallIntegerField(default=7, help_text='Укажите периодичность выполнения', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность')),
                ('prize', models.CharField(blank=True, help_text='Укажите вознаграждение', max_length=150, null=True, verbose_name='Вознаграждение')),
                ('lead_time', models.TimeField(default='00:02:00', help_text='Укажите время на выполнение привычки', verbose_name='Время на выполнение')),
                ('public_habit', models.BooleanField(help_text='Укажите признак публичности', verbose_name='Признак публичности')),
                ('associated_habit', models.ForeignKey(blank=True, help_text='Укажите связанную привычку', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
