# Generated by Django 5.1 on 2024-08-12 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='Укажите место выполнения', max_length=150, null=True, verbose_name='Место')),
                ('time', models.TimeField(auto_now_add=True, help_text='Укажите время выполнения', null=True, verbose_name='Время')),
                ('action', models.CharField(blank=True, help_text='Укажите действие привычки', null=True, verbose_name='Действие')),
                ('nice_habit', models.BooleanField(blank=True, help_text='Укажите признак приятной привычки', null=True, verbose_name='Признак привычки')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='Укажите периодичность выполнения', verbose_name='Периодичность')),
                ('prize', models.CharField(blank=True, help_text='Укажите вознаграждение', max_length=150, null=True, verbose_name='Вознаграждение')),
                ('lead_time', models.TimeField(default='00:02:00', help_text='Укажите время на выполнение привычки', verbose_name='Время на выполнение')),
                ('public_habit', models.BooleanField(default=True, help_text='Укажите признак публичности', verbose_name='Признак публичности')),
                ('associated_habit', models.ForeignKey(blank=True, help_text='Укажите связанную привычку', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='Связанная привычка')),
                ('author', models.ForeignKey(help_text='Укажите автора привычки', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
