# Generated by Django 5.1 on 2024-08-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(help_text='Укажите действие привычки', verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='location',
            field=models.CharField(help_text='Укажите место выполнения', max_length=150, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(auto_now_add=True, help_text='Укажите время выполнения', verbose_name='Время'),
        ),
    ]
