# Generated by Django 5.1 on 2024-08-12 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_action_alter_habit_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Укажите автора привычки', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='nice_habit',
            field=models.BooleanField(help_text='Укажите признак приятной привычки', verbose_name='Признак привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='public_habit',
            field=models.BooleanField(help_text='Укажите признак публичности', verbose_name='Признак публичности'),
        ),
    ]
