# Generated by Django 5.1 on 2024-08-12 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_author_alter_habit_nice_habit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 12, 13, 53, 12, 475036), help_text='Укажите время выполнения', verbose_name='Время'),
        ),
    ]
